### ISSUE TITLE
any chances we can add items to a whitelist in a config file?

### ISSUE THREAD

**Issue by majijn** [pentantan/SauceConstruct#2]
and maybe even oredict entries, I dont seem to have any sauces considered valid by this mod. I'm using bird's foods and vanilla, with a couple of other misc mods

**Comment by pentantan** [comment]
It is add in 1.1.2

**Comment by majijn** [comment]
thanks! can you clarify how to add the items to the config? I tried adding rustic:chili_pepper
but it doesnt seem to accept it =/

**Comment by majijn** [comment]
I still havent been able to make it work, what's the syntax for adding items in the config file?
